name: Sequence CI/CD Pipeline
on: [push]
jobs:
  Test-Multiply:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test



