name: Sequence CI/CD Pipeline
on: [push]
jobs:
  Test-Multiply:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
  Lint:
    # needs: Test-Multiply
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.14"
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint






